CREATE TABLE MEMBER (
    MEMBER_ID VARCHAR2(30) PRIMARY KEY,
    MEMBER_PWD VARCHAR2(30) NOT NULL,
    MEMBER_NAME VARCHAR2(30) NOT NULL,
    GENDER VARCHAR2(10) CHECK (GENDER IN('M','F')),
    EMAIL VARCHAR2(50) NOT NULL,
    AGE NUMBER,
    ENROLL_DATE DATE DEFAULT SYSDATE
);

CREATE TABLE CHARACTER (
    CRT_NO NUMBER PRIMARY KEY,
    CRT_NAME VARCHAR2(30) NOT NULL,
    CRT_CLASS VARCHAR2(30) NOT NULL,
    CRT_LEVEL NUMBER DEFAULT '1',
    CRT_ONWER VARCHAR(20) REFERENCES MEMBER(MEMBER_ID),
    DELETE_YN VARCHAR2(10) DEFAULT 'N',
    CHECK (DELETE_YN IN('Y','N'))
);

CREATE SEQUENCE SEQ_CRT;

ALTER TABLE CHARACTER
RENAME TO CRT;

ALTER TABLE CRT    
RENAME COLUMN CRT_ONWER TO CRT_OWNER;